version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: "src/infra"
          checkout: true
          context: terraform
      - terraform/validate:
          path: "src/infra"
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: "src/infra"
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          path: "src/infra"
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: dev/apply
          requires:
            - terraform/plan