# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  terraform: circleci/terraform@2.1.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: "src/infra"
          checkout: true
          context: terraform
      - terraform/validate:
          path: "src/infra"
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: "src/infra"
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          path: "src/infra"
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: dev/apply
          requires:
            - terraform/plan